---
language: "python"
python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - "pip install -U pip flake8 pep257"
  - "python setup.py build"
  - "python setup.py bdist --formats=zip"
  - "sudo python setup.py install"

script:
  - "flake8 --ignore=E501 ./fido"
  # pep257: fido.py is WIP
  - 'pep257 --match="(?!fido).*\.py" ./fido'
  - "python setup.py test"
